# Rcmdr demo script =============================
# by Melinda Higgins
# dated 03/18/2024

# load Rcmdr package and launch interface
library(Rcmdr)

# load some datasets in memory to play with
library(palmerpenguins)
data(penguins)

# load the penguins dataset and 
# try out some plotting and
# descriptive stats
# and maybe cluster analysis or PCA

# the save your R script 
# and save Rmarkdown generated by Rcmdr

